version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: quiz-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: quiz_platform
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - quiz-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/quiz_platform --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Authentication Service
  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: quiz-auth-service
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/quiz_platform?authSource=admin
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - quiz-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../src:/app/src
      - ../frontend:/app/frontend

volumes:
  mongodb_data:

networks:
  quiz-network:
    driver: bridge
